In [1]:
menu = ['Pizza', 'Burger', 'Salad']

[x.upper() for x in menu if x == 'Pizza']

['PIZZA']

In [2]:
menu_with_price = {
    'Pizza' : 5,
    'Burger' : 3,
    'Salad' : 2,
}
[x for x in menu_with_price if menu_with_price[x] > 2]

['Pizza', 'Burger']

In [3]:
numbers = [1, 2, 3, 4, 5]

In [4]:
import numpy as np
import pandas as pd

In [5]:
scores = np.array([85,90, 78, 92, 88])

print(scores.size)

5

In [6]:
print(scores[-2:])

[92 88]

In [7]:
scores[0] = 75
print(scores)

[75 90 78 92 88]

In [8]:
scores = scores + 5
print(scores)

[80 95 83 97 93]

In [9]:
scores = scores / 100
print(scores)

scores = scores ** 2
print(scores)

[0.8  0.95 0.83 0.97 0.93]
[0.64   0.9025 0.6889 0.9409 0.8649]

In [10]:
print('Sum of scores:', np.sum(scores))
print('Average of scores:', scores.mean())
print('Minimum score:', scores.min())
print('Maximum score:', scores.max())

Sum of scores: 4.0372
Average of scores: 0.80744
Minimum score: 0.6400000000000001
Maximum score: 0.9409

In [11]:
distance = np.array([120, 80, 90, 220])

In [12]:
miles = distance * .63
print(miles)

[ 75.6  50.4  56.7 138.6]

In [13]:
score = np.array([72, 85, 68, 88])
print(score)

[72 85 68 88]

In [15]:
passed = score >= 80
print(passed)

score[passed]

[False  True False  True]

array([85, 88])

In [22]:
print(score[score > score.mean()].mean())

86.5

In [25]:
scores = np.array([
    [72, 80, 75],
    [90, 88, 94],
    [65, 70, 60]
])

print(scores)

[[72 80 75]
 [90 88 94]
 [65 70 60]]

In [27]:
print(scores.shape)

(3, 3)

In [36]:
print(scores[1:,0:2].mean())

78.25

In [40]:
print(scores[:,0].max())

90

In [42]:
name = ['Avery', 'Jordan', 'Morgan', 'Riley']
hours = [4, 7, 4, 6]
grade = [72, 91, 68, 88]

students = pd.DataFrame({
    'name' : name,
    'hours_studied' : hours,
    'grade' : grade
})

print(students)

     name  hours_studied  grade
0   Avery              4     72
1  Jordan              7     91
2  Morgan              4     68
3   Riley              6     88

In [49]:
students[['grade']] #Full dataFrame pack

   grade
0     72
1     91
2     68
3     88

In [50]:
students['grade'] #A series of value

0    72
1    91
2    68
3    88
Name: grade, dtype: int64

In [52]:
students.describe()

       hours_studied      grade
count           4.00   4.000000
mean            5.25  79.750000
std             1.50  11.441882
min             4.00  68.000000
25%             4.00  71.000000
50%             5.00  80.000000
75%             6.25  88.750000
max             7.00  91.000000

In [53]:
students[students['grade'] > 80].describe()

       hours_studied     grade
count       2.000000   2.00000
mean        6.500000  89.50000
std         0.707107   2.12132
min         6.000000  88.00000
25%         6.250000  88.75000
50%         6.500000  89.50000
75%         6.750000  90.25000
max         7.000000  91.00000